# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24dd2339d80376f42499b7d520c93a0699980787ea409b8edd22edcc6e048cea6dde2b19a357a2366a033b874558d4268f28c262c6b8814d65e94bf2a13836d9

test:
  secret_key_base: 1dd117c85df57c893a9dc9fc2476699996537f0ae14275379331ec00c0a18ad1a3880f5cac2c2b5cbfb5cd17fe4bdaa910e90856d23ce27a8979022807b62852

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
